SELECT 
    I.ITEM_ID, I.ITEM_NAME
FROM
    ITEM_INFO AS I 
    JOIN (
        SELECT ITEM_ID
        FROM ITEM_TREE
        WHERE PARENT_ITEM_ID IS NULL
    ) AS R
    ON I.ITEM_ID = R.ITEM_ID
ORDER BY 1;
