SELECT G3.ID
FROM ECOLI_DATA AS G1
    JOIN ECOLI_DATA AS G2 ON G1.ID = G2.PARENT_ID 
    JOIN ECOLI_DATA AS G3 ON G2.ID = G3.PARENT_ID
WHERE G1.PARENT_ID IS NULL
ORDER BY G3.ID;

# G1              G2
# ID PARENT_ID    ID PARENT_ID 
# 1  NULL         3  1 
# 2  NULL         4  2
# 2  NULL         4  2
