SELECT P.ID, IFNULL(C.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS P LEFT JOIN
    (
        SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT
        FROM ECOLI_DATA
        GROUP BY PARENT_ID
    ) AS C
    ON P.ID = C.PARENT_ID
ORDER BY P.ID