SELECT P.PRODUCT_CODE, S.AMOUNT*P.PRICE AS SALES
FROM 
    PRODUCT AS P JOIN
    (
        SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT 
        FROM OFFLINE_SALE AS O
        GROUP BY PRODUCT_ID 
    ) AS S
    ON P.PRODUCT_ID = S.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE;