SELECT 
    P.PRODUCT_CODE,
    P.PRICE * S.SALES_TOTAL AS SALES
FROM 
    PRODUCT AS P
    JOIN (
        SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_TOTAL
        FROM OFFLINE_SALE 
        GROUP BY PRODUCT_ID
    ) AS S
    ON P.PRODUCT_ID = S.PRODUCT_ID
ORDER BY
    SALES DESC, P.PRODUCT_CODE;