-- 코드를 입력하세요
-- 2022년 3월의 오프라인/온라인 상품 판매 데이터의 판매 날짜, 상품ID, 유저ID, 판매량을 출력
-- OFFLINE_SALE 테이블의 판매 데이터의 USER_ID 값은 NULL 로 표시
-- 판매일을 기준으로 오름차순 정렬 > 상품 ID 오름차순 > 유저 ID 오름차순

SELECT DATE_FORMAT(S.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, S.PRODUCT_ID, S.USER_ID, S.SALES_AMOUNT
FROM (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE 
    WHERE SALES_DATE LIKE '2022-03%'
    UNION 
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE 
    WHERE SALES_DATE LIKE '2022-03%'
    ) AS S
ORDER BY S.SALES_DATE, S.PRODUCT_ID, S.USER_ID