-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중에서 
-- 2022-11-01부터 2022-11-30까지 대여 가능하고
-- 30일 간의 대여 금액이 50만원 이상 200만원 미만인
-- 자동차 ID, 종류, 대여 금액(FEE) 출력
-- 대여 금액 기준 내림차순 > 자동차 종류 > 자동차 ID 내림차순

SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*(1-P.DISCOUNT_RATE/100)*30,0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON C.CAR_TYPE = P.CAR_TYPE
WHERE NOT EXISTS (SELECT CAR_ID
             FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
             WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
                AND C.CAR_ID = H.CAR_ID)
    AND C.CAR_TYPE IN ('세단', 'SUV') 
    AND P.DURATION_TYPE LIKE '30%'
    AND ROUND(C.DAILY_FEE*(1-P.DISCOUNT_RATE/100)*30,0) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;