SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM 
    (
        SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
        FROM ANIMAL_INS
        WHERE SEX_UPON_INTAKE LIKE '%Intact%'
    ) AS I 
    JOIN 
    (
        SELECT ANIMAL_ID
        FROM ANIMAL_OUTS
        WHERE SEX_UPON_OUTCOME REGEXP 'Spayed|Neutered'
    ) AS O
    ON I.ANIMAL_ID = O.ANIMAL_ID