SELECT 
    YEAR(O.SALES_DATE) AS YEAR, 
    MONTH(O.SALES_DATE) AS MONTH, 
    U.GENDER, 
    COUNT(DISTINCT O.USER_ID) AS USERS
FROM
    (
        SELECT USER_ID, GENDER
        FROM USER_INFO
        WHERE GENDER IS NOT NULL
    ) AS U 
    JOIN
        ONLINE_SALE AS O
    ON 
        U.USER_ID = O.USER_ID
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER
ORDER BY 1,2,3;