-- 코드를 작성해주세요

SELECT COUNT(*) AS FISH_COUNT, N.FISH_NAME
FROM FISH_NAME_INFO AS N LEFT JOIN FISH_INFO AS I ON N.FISH_TYPE = I.FISH_TYPE
GROUP BY N.FISH_NAME
HAVING COUNT(*)
ORDER BY FISH_COUNT DESC;
