# 물고기 종류별 물고기의 이름과 작읍 수를 출력하는 sql문
SELECT 
    COUNT(I.FISH_TYPE) AS FISH_COUNT,
    N.FISH_NAME
FROM
    FISH_INFO AS I
    JOIN FISH_NAME_INFO AS N
    ON I.FISH_TYPE = N.FISH_TYPE
GROUP BY
    I.FISH_TYPE
ORDER BY
    FISH_COUNT DESC;