SELECT 
    H.HISTORY_ID,
    ROUND(C.DAILY_FEE * (1-IFNULL(P.DISCOUNT_RATE, 0)/100)) * H.DURATION AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR AS C
    JOIN (
        SELECT 
            HISTORY_ID, CAR_ID, 
            DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION,
            CASE
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
                ELSE '7일 이하'
            END AS DURATION_TYPE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    ) AS H
        ON C.CAR_ID = H.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
        ON H.DURATION_TYPE = P.DURATION_TYPE
        AND C.CAR_TYPE = P.CAR_TYPE
WHERE 
    C.CAR_TYPE = '트럭'
ORDER BY 
    FEE DESC, H.HISTORY_ID DESC;