SELECT 
    I.HISTORY_ID,
    FLOOR(I.DAILY_FEE*(1-IFNULL(P.DISCOUNT_RATE,0)/100)*I.RENTAL_DURATION) AS FEE
FROM 
    ( 
        SELECT
            H.HISTORY_ID,
            C.CAR_ID,
            C.DAILY_FEE,
            C.CAR_TYPE,
            DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_DURATION,
            CASE 
                WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
                WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
                WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL
            END AS DURATION_TYPE 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
        JOIN CAR_RENTAL_COMPANY_CAR AS C
        ON C.CAR_ID = H.CAR_ID
        WHERE C.CAR_TYPE = '트럭'
    ) AS I
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON I.CAR_TYPE = P.CAR_TYPE 
    AND I.DURATION_TYPE = P.DURATION_TYPE
ORDER BY 
    2 DESC, 1 DESC;