SELECT H.FLAVOR
FROM (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS HALF_TOTAL_ORDER
        FROM FIRST_HALF
        GROUP BY FLAVOR
    ) AS H
    JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR
    ) AS J 
    ON H.FLAVOR = J.FLAVOR
ORDER BY JULY_TOTAL_ORDER + HALF_TOTAL_ORDER DESC
LIMIT 3;