SELECT H.FLAVOR
FROM
        (
            SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_JULY
            FROM JULY
            GROUP BY FLAVOR
        ) AS J 
    JOIN
        (
            SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_HALF
            FROM FIRST_HALF 
            GROUP BY FLAVOR
        ) AS H
    ON
        J.FLAVOR = H.FLAVOR  
ORDER BY J.TOTAL_JULY + H.TOTAL_HALF DESC
LIMIT 3;