
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM
    (
        SELECT APNT_YMD, APNT_NO, PT_NO, MDDR_ID
        FROM APPOINTMENT
        WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
            AND APNT_CNCL_YN = 'N'
            AND MCDP_CD = 'CS'
    ) AS A
    JOIN DOCTOR AS D 
        ON D.DR_ID = A.MDDR_ID
    JOIN PATIENT AS P 
        ON P.PT_NO = A.PT_NO
ORDER BY 
    A.APNT_YMD;