SELECT
    E.EMP_NO,
    E.EMP_NAME,
    CASE 
        WHEN G.AVG_SCORE >= 96 THEN 'S'
        WHEN G.AVG_SCORE >= 90 THEN 'A'
        WHEN G.AVG_SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE 
        WHEN G.AVG_SCORE >= 96 THEN E.SAL * 0.2
        WHEN G.AVG_SCORE >= 90 THEN E.SAL * 0.15
        WHEN G.AVG_SCORE >= 80 THEN E.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM (
        SELECT EMP_NO, AVG(SCORE) AS AVG_SCORE
        FROM HR_GRADE 
        GROUP BY EMP_NO
    ) AS G
    JOIN (
        SELECT EMP_NO, EMP_NAME, SAL
        FROM HR_EMPLOYEES
    ) AS E
    ON G.EMP_NO = E.EMP_NO