-- 코드를 입력하세요
# 2021년에 출판된 인문 카테고리에 속하는 도서 리스트 중
# 도서 ID와 출판일 출력
# 출판일 오름차순
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021 AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE;