SELECT B.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM 
    BOOK AS B JOIN
    (
        SELECT BOOK_ID, SALES
        FROM BOOK_SALES
        WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01'
    ) AS S
    ON B.BOOK_ID = S.BOOk_ID
GROUP BY B.CATEGORY
ORDER BY 1;