# 카테고리별 도서 총 판매량, 카테고리
SELECT
    B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM
    BOOK AS B
    JOIN (
        SELECT BOOK_ID, SALES
        FROM BOOK_SALES
        WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
    ) AS S
    ON B.BOOK_ID = S.BOOK_ID
GROUP BY
    B.CATEGORY
ORDER BY
    1;