SELECT P.CATEGORY, C.MAX_PRICE, P.PRODUCT_NAME
FROM 
    FOOD_PRODUCT AS P
    JOIN (
            SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
            FROM FOOD_PRODUCT 
            GROUP BY CATEGORY
         ) AS C
    ON P.CATEGORY = C.CATEGORY
    AND P.PRICE = C.MAX_PRICE
WHERE P.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY C.MAX_PRICE DESC;